apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dhrem-research
  annotations:
    # Cloud Run configuration
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        # Resource configuration
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
        
        # Timeout configuration
        run.googleapis.com/timeout: "300s"
        
        # Service account for Secret Manager access
        run.googleapis.com/service-account: "dhrem-research@decoded-app-457000-s2.iam.gserviceaccount.com"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/decoded-app-457000-s2/dhrem-research:latest
        name: dhrem-research
        ports:
        - name: http1
          containerPort: 4001
        env:
        - name: NODE_ENV
          value: "production"
        - name: GOOGLE_CLOUD_PROJECT
          value: "decoded-app-457000-s2"
        - name: GOOGLE_CLOUD_PROJECT_ID
          value: "decoded-app-457000-s2"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4001
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true 